#!ek9
<?-
  Test IR generation for simple try/catch.
  Try block executes successfully (no exception thrown).
  Catch handler present but not executed.
-?>
defines module exceptionHandling

  defines function

    @IR: IR_GENERATION: FUNCTION: "exceptionHandling::simpleTryCatch": `
    ConstructDfn: exceptionHandling::simpleTryCatch()->org.ek9.lang::Void
    OperationDfn: exceptionHandling::simpleTryCatch.c_init()->org.ek9.lang::Void
    BasicBlock: _entry_1
    RETURN
    OperationDfn: exceptionHandling::simpleTryCatch.i_init()->org.ek9.lang::Void
    BasicBlock: _entry_1
    RETURN
    OperationDfn: exceptionHandling::simpleTryCatch.simpleTryCatch()->exceptionHandling::simpleTryCatch  // ./simpleTryCatch.ek9:100:5
    BasicBlock: _entry_1
    CALL (exceptionHandling::simpleTryCatch)this.i_init() [pure=false, complexity=0]  // ./simpleTryCatch.ek9:100:5
    RETURN this  // ./simpleTryCatch.ek9:100:5
    OperationDfn: exceptionHandling::simpleTryCatch._call()->org.ek9.lang::Void  // ./simpleTryCatch.ek9:100:5
    BasicBlock: _entry_1
    SCOPE_ENTER _scope_1  // ./simpleTryCatch.ek9:101:7
    REFERENCE stdout, org.ek9.lang::Stdout  // ./simpleTryCatch.ek9:101:7
    _temp1 = CALL (org.ek9.lang::Stdout)org.ek9.lang::Stdout.<init>() [pure=true, complexity=1, effects=IO,RETURN_MUTATION]  // ./simpleTryCatch.ek9:101:17
    RETAIN _temp1  // ./simpleTryCatch.ek9:101:17
    SCOPE_REGISTER _temp1, _scope_1  // ./simpleTryCatch.ek9:101:17
    STORE stdout, _temp1  // ./simpleTryCatch.ek9:101:17
    RETAIN stdout  // ./simpleTryCatch.ek9:101:17
    SCOPE_REGISTER stdout, _scope_1  // ./simpleTryCatch.ek9:101:17
    SCOPE_ENTER _scope_2  // ./simpleTryCatch.ek9:103:7
    SCOPE_ENTER _scope_3  // ./simpleTryCatch.ek9:103:7
    CONTROL_FLOW_CHAIN  // ./simpleTryCatch.ek9:103:7
    [
    chain_type: "TRY_CATCH_FINALLY"
    try_block_details:
    [
    try_scope_id: _scope_4
    try_body_evaluation:
    [
    SCOPE_ENTER _scope_4  // ./simpleTryCatch.ek9:103:7
    _temp3 = LOAD stdout  // ./simpleTryCatch.ek9:104:9
    RETAIN _temp3  // ./simpleTryCatch.ek9:104:9
    SCOPE_REGISTER _temp3, _scope_4  // ./simpleTryCatch.ek9:104:9
    _temp4 = LOAD_LITERAL Try block executing, org.ek9.lang::String  // ./simpleTryCatch.ek9:104:24
    RETAIN _temp4  // ./simpleTryCatch.ek9:104:24
    SCOPE_REGISTER _temp4, _scope_4  // ./simpleTryCatch.ek9:104:24
    CALL (org.ek9.lang::Stdout)_temp3.println(_temp4) [pure=true, complexity=1]  // ./simpleTryCatch.ek9:104:16
    REFERENCE value, org.ek9.lang::Integer  // ./simpleTryCatch.ek9:105:9
    _temp5 = LOAD_LITERAL 42, org.ek9.lang::Integer  // ./simpleTryCatch.ek9:105:18
    RETAIN _temp5  // ./simpleTryCatch.ek9:105:18
    SCOPE_REGISTER _temp5, _scope_4  // ./simpleTryCatch.ek9:105:18
    STORE value, _temp5  // ./simpleTryCatch.ek9:105:18
    RETAIN value  // ./simpleTryCatch.ek9:105:18
    SCOPE_REGISTER value, _scope_4  // ./simpleTryCatch.ek9:105:18
    _temp7 = LOAD stdout  // ./simpleTryCatch.ek9:106:9
    RETAIN _temp7  // ./simpleTryCatch.ek9:106:9
    SCOPE_REGISTER _temp7, _scope_4  // ./simpleTryCatch.ek9:106:9
    _temp8 = LOAD value  // ./simpleTryCatch.ek9:106:24
    RETAIN _temp8  // ./simpleTryCatch.ek9:106:24
    SCOPE_REGISTER _temp8, _scope_4  // ./simpleTryCatch.ek9:106:24
    CALL (org.ek9.lang::StringOutput)_temp7.println(_temp8) [pure=true, complexity=1, trait=true]  // ./simpleTryCatch.ek9:106:16
    SCOPE_EXIT _scope_4  // ./simpleTryCatch.ek9:103:7
    ]
    ]
    condition_chain:
    [
    [
    case_scope_id: _scope_5
    case_type: "EXCEPTION_HANDLER"
    condition_evaluation:
    [
    ]
    body_evaluation:
    [
    SCOPE_ENTER _scope_5  // ./simpleTryCatch.ek9:107:7
    REFERENCE ex, org.ek9.lang::Exception  // ./simpleTryCatch.ek9:107:7
    SCOPE_REGISTER ex, _scope_5  // ./simpleTryCatch.ek9:107:7
    _temp10 = LOAD stdout  // ./simpleTryCatch.ek9:109:9
    RETAIN _temp10  // ./simpleTryCatch.ek9:109:9
    SCOPE_REGISTER _temp10, _scope_5  // ./simpleTryCatch.ek9:109:9
    _temp11 = LOAD_LITERAL Caught exception, org.ek9.lang::String  // ./simpleTryCatch.ek9:109:24
    RETAIN _temp11  // ./simpleTryCatch.ek9:109:24
    SCOPE_REGISTER _temp11, _scope_5  // ./simpleTryCatch.ek9:109:24
    CALL (org.ek9.lang::Stdout)_temp10.println(_temp11) [pure=true, complexity=1]  // ./simpleTryCatch.ek9:109:16
    SCOPE_EXIT _scope_5  // ./simpleTryCatch.ek9:107:7
    ]
    exception_type: "org.ek9.lang::Exception"
    exception_variable: ex
    ]
    ]
    scope_id: _scope_3
    ]
    SCOPE_EXIT _scope_3  // ./simpleTryCatch.ek9:103:7
    SCOPE_EXIT _scope_2  // ./simpleTryCatch.ek9:103:7
    SCOPE_EXIT _scope_1  // ./simpleTryCatch.ek9:101:7
    RETURN  // ./simpleTryCatch.ek9:100:5`
    simpleTryCatch()
      stdout <- Stdout()

      try
        stdout.println("Try block executing")
        value <- 42
        stdout.println(value)
      catch
        -> ex as Exception
        stdout.println("Caught exception")
//EOF
